package com.cadie.futbolsim.domain.models

import com.cadie.futbolsim.data.local.entities.PartidoEntity
import com.cadie.futbolsim.data.remote.PartidoDto

data class Partido(
    val id: String,
    val liga: String,
    val equipoLocal: String,
    val equipoVisitante: String,
    val fechaReal: Long,
    val fechaSimulacion: Long?,
    val jornada: Int,
    val temporada: String,
    val estado: String,
    
    val golesLocalSim: Int?,
    val golesVisitanteSim: Int?,
    val rematesLocalSim: Int?,
    val rematesVisitanteSim: Int?,
    val rematesPuertaLocalSim: Int?,
    val rematesPuertaVisitanteSim: Int?,
    val tarjetasLocalSim: Int?,
    val tarjetasVisitanteSim: Int?,
    val tarjetasRojasLocalSim: Int?,
    val tarjetasRojasVisitanteSim: Int?,
    val cornersLocalSim: Int?,
    val cornersVisitanteSim: Int?,
    
    val golesLocalReal: Int?,
    val golesVisitanteReal: Int?,
    val rematesLocalReal: Int?,
    val rematesVisitanteReal: Int?,
    val rematesPuertaLocalReal: Int?,
    val rematesPuertaVisitanteReal: Int?,
    val tarjetasLocalReal: Int?,
    val tarjetasVisitanteReal: Int?,
    val cornersLocalReal: Int?,
    val cornersVisitanteReal: Int?,
    
    val acertado: Boolean?,
    val margenError: Double?,
    val errorTotal: Double?,
    val factoresUtilizados: String,
    val datosInsuficientes: Boolean,
    val confianza: Int,
    val resumenTexto: String,
    val sincronizado: Boolean,
    val fechaCreacion: Long,
    val esSimulacionHistorica: Boolean,
    val simulacionTipo: String
) {
    val tieneSimulacion: Boolean
        get() = fechaSimulacion != null

    val yaDisputado: Boolean
        get() = estado == "finalizado"
}

fun PartidoEntity.toDomain() = Partido(
    id = id,
    liga = liga,
    equipoLocal = equipo_local,
    equipoVisitante = equipo_visitante,
    fechaReal = fecha_real,
    fechaSimulacion = fecha_simulacion,
    jornada = jornada,
    temporada = temporada,
    estado = estado,
    golesLocalSim = goles_local_sim,
    golesVisitanteSim = goles_visitante_sim,
    rematesLocalSim = remates_local_sim,
    rematesVisitanteSim = remates_visitante_sim,
    rematesPuertaLocalSim = remates_puerta_local_sim,
    rematesPuertaVisitanteSim = remates_puerta_visitante_sim,
    tarjetasLocalSim = tarjetas_local_sim,
    tarjetasVisitanteSim = tarjetas_visitante_sim,
    tarjetasRojasLocalSim = tarjetas_rojas_local_sim,
    tarjetasRojasVisitanteSim = tarjetas_rojas_visitante_sim,
    cornersLocalSim = corners_local_sim,
    cornersVisitanteSim = corners_visitante_sim,
    golesLocalReal = goles_local_real,
    golesVisitanteReal = goles_visitante_real,
    rematesLocalReal = remates_local_real,
    rematesVisitanteReal = remates_visitante_real,
    rematesPuertaLocalReal = remates_puerta_local_real,
    rematesPuertaVisitanteReal = remates_puerta_visitante_real,
    tarjetasLocalReal = tarjetas_local_real,
    tarjetasVisitanteReal = tarjetas_visitante_real,
    cornersLocalReal = corners_local_real,
    cornersVisitanteReal = corners_visitante_real,
    acertado = acertado,
    margenError = margen_error,
    errorTotal = error_total,
    factoresUtilizados = factores_utilizados,
    datosInsuficientes = datos_insuficientes,
    confianza = confianza,
    resumenTexto = resumen_texto,
    sincronizado = sincronizado,
    fechaCreacion = fecha_creacion,
    esSimulacionHistorica = es_simulacion_historica,
    simulacionTipo = simulacion_tipo
)

fun PartidoDto.toDomain() = Partido(
    id = id,
    liga = liga,
    equipoLocal = equipo_local,
    equipoVisitante = equipo_visitante,
    fechaReal = fecha_real,
    fechaSimulacion = fecha_simulacion,
    jornada = jornada,
    temporada = temporada,
    estado = estado,
    golesLocalSim = goles_local_sim,
    golesVisitanteSim = goles_visitante_sim,
    rematesLocalSim = remates_local_sim,
    rematesVisitanteSim = remates_visitante_sim,
    rematesPuertaLocalSim = remates_puerta_local_sim,
    rematesPuertaVisitanteSim = remates_puerta_visitante_sim,
    tarjetasLocalSim = tarjetas_local_sim,
    tarjetasVisitanteSim = tarjetas_visitante_sim,
    tarjetasRojasLocalSim = tarjetas_rojas_local_sim,
    tarjetasRojasVisitanteSim = tarjetas_rojas_visitante_sim,
    cornersLocalSim = corners_local_sim,
    cornersVisitanteSim = corners_visitante_sim,
    golesLocalReal = goles_local_real,
    golesVisitanteReal = goles_visitante_real,
    rematesLocalReal = remates_local_real,
    rematesVisitanteReal = remates_visitante_real,
    rematesPuertaLocalReal = remates_puerta_local_real,
    rematesPuertaVisitanteReal = remates_puerta_visitante_real,
    tarjetasLocalReal = tarjetas_local_real,
    tarjetasVisitanteReal = tarjetas_visitante_real,
    cornersLocalReal = corners_local_real,
    cornersVisitanteReal = corners_visitante_real,
    acertado = acertado,
    margenError = margen_error,
    errorTotal = error_total,
    factoresUtilizados = factores_utilizados,
    datosInsuficientes = datos_insuficientes,
    confianza = confianza,
    resumenTexto = resumen_texto,
    sincronizado = true,
    fechaCreacion = System.currentTimeMillis(),
    esSimulacionHistorica = es_simulacion_historica,
    simulacionTipo = simulacion_tipo
)

fun Partido.toEntity() = PartidoEntity(
    id = id,
    liga = liga,
    equipo_local = equipoLocal,
    equipo_visitante = equipoVisitante,
    fecha_real = fechaReal,
    fecha_simulacion = fechaSimulacion,
    jornada = jornada,
    temporada = temporada,
    estado = estado,
    goles_local_sim = golesLocalSim,
    goles_visitante_sim = golesVisitanteSim,
    remates_local_sim = rematesLocalSim,
    remates_visitante_sim = rematesVisitanteSim,
    remates_puerta_local_sim = rematesPuertaLocalSim,
    remates_puerta_visitante_sim = rematesPuertaVisitanteSim,
    tarjetas_local_sim = tarjetasLocalSim,
    tarjetas_visitante_sim = tarjetasVisitanteSim,
    tarjetas_rojas_local_sim = tarjetasRojasLocalSim,
    tarjetas_rojas_visitante_sim = tarjetasRojasVisitanteSim,
    corners_local_sim = cornersLocalSim,
    corners_visitante_sim = cornersVisitanteSim,
    goles_local_real = golesLocalReal,
    goles_visitante_real = golesVisitanteReal,
    remates_local_real = rematesLocalReal,
    remates_visitante_real = rematesVisitanteReal,
    remates_puerta_local_real = rematesPuertaLocalReal,
    remates_puerta_visitante_real = rematesPuertaVisitanteReal,
    tarjetas_local_real = tarjetasLocalReal,
    tarjetas_visitante_real = tarjetasVisitanteReal,
    corners_local_real = cornersLocalReal,
    corners_visitante_real = cornersVisitanteReal,
    acertado = acertado,
    margen_error = margenError,
    error_total = errorTotal,
    factores_utilizados = factoresUtilizados,
    datos_insuficientes = datosInsuficientes,
    confianza = confianza,
    resumen_texto = resumenTexto,
    sincronizado = sincronizado,
    fecha_creacion = fechaCreacion,
    es_simulacion_historica = esSimulacionHistorica,
    simulacion_tipo = simulacionTipo
)
